apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentinel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alhennessey92/traders_guild_main_build.git'
    targetRevision: HEAD
    path: infrastructure/dev/redis-sentinel
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true