# timescaledb-argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timescaledb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alhennessey92/traders_guild_main_build.git'   # Your Git repo
    targetRevision: HEAD
    path: infrastructure/dev/timescaledb   # Folder in repo containing above YAMLs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: timescale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true