# timescaledb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: timescale
spec:
  type: ClusterIP
  selector:
    app: timescaledb
  ports:
    - port: 5432
      targetPort: 5432