apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alhennessey92/traders_guild_infra_kong.git  # ✅ Your GitHub repo
    targetRevision: main  # ✅ Ensure this matches your branch name
    path: kong  # ✅ The folder where values.yaml is located
    helm:
      valueFiles:
        - values.yaml  # ✅ Since ArgoCD starts in 'kong/', this works
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true