apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kong
    repoURL: https://charts.konghq.com
    targetRevision: "latest"
    helm:
      values: |
        ingressController:
          enabled: true
          installCRDs: false
        env:
          database: "off"
          plugins: "bundled"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true