apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/alhennessey92/traders_guild_main_build.git'
    targetRevision: HEAD
    path: fastapi-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true