apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: "kong"
    external-dns.alpha.kubernetes.io/hostname: "api.tg-backend.com"
spec:
  rules:
    - host: api.tg-backend.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kong-proxy
                port:
                  number: 80
  tls:
    - hosts:
        - api.tg-backend.com
      secretName: kong-tls