apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-cert
  namespace: kong
spec:
  secretName: kong-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.tg-backend.com