resources:
  - namespace.yaml
  - https://charts.konghq.com/kong/kong-2.30.0.tgz

helmCharts:
  - name: kong
    releaseName: kong
    version: "2.30.0"
    namespace: kong
    valuesFile: kong-values.yaml