ingressController:
  enabled: true
  installCRDs: true
proxy:
  type: NodePort
  nodePort: 30000  # Fixed port for external access
admin:
  enabled: true
  type: ClusterIP
postgresql:
  enabled: false
env:
  database: "off"