apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
 name: tg-consumer             # Unique name for this consumer
 namespace: kong
 annotations:
  kubernetes.io/ingress.class: kong
username: tg-consumer-user               # Username for this consumer
custom_id: tg-consumer-1             # Unique ID for this consumer
credentials:
 - user1-apikey                 # Name of the Secret containing the API key