apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: tg-rate-limit     # Must match name in Ingress annotation
 namespace: kong
 annotations:
  kubernetes.io/ingress.class: kong
config:
 minute: 10     # Number of requests allowed per minute
 limit_by: consumer
 policy: local
plugin: rate-limiting