apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: tg-ingress
 namespace: kong
 annotations:
   konghq.com/strip-path: "false"
  #  konghq.com/plugins: <auth-plugin-name>, <ratelimit-plugin-name>    # Plugin names referenced in KongPlugin resources
   kubernetes.io/ingress.class: kong
   konghq.com/methods: "GET, POST"  
spec:
 ingressClassName: kong
 rules:
   - http:
       paths:
         - path: /api
           pathType: Prefix
           backend:
             service:
               name: tg-ingress-api   # Name of your K8s Service
               port:
                 number: 3000    # Port exposed by your Service